package com.example.jetpackcompose.ui.common


enum class Screens(val displayName: String) {

    // SplashScreen("Splash Screen"),
    BoxJC("Box JC"),
    ConstraintJC("Constraint JC"),
    ConstraintJC2("Constraint JC2"),
    ButtonTextJC("Button Text JC"),
    ColumnJC("Column JC"),
    RowJC("Row JC"),
    TestThemes("Test Themes"),
    SnackBarJC("SnackBar JC"),
    PullRefreshJC("Pull Refresh JC"),
    VerticalPager("Vertical Pager"),
    LazyColumnJC("Lazy Column JC"),
    LazyColumnJC2("Lazy Column JC2"),
    LazyRowJC("Lazy Row JC"),
    LazyVerticalGridJC("Lazy Vertical Grid JC"),
    LazyHorizontalGridJC("Lazy Horizontal Grid JC"),
    LazyColumnDragAndDrop("Lazy Column Drag and Drop"),
    LazyVerticalGridDragAndDrop("Vertical Grid Drag and Drop"),
    CounterScreen("Counter Screen"),
    ViewMutableStateExample("View Mutable State Example"),
    CatNavigation("Cat Navigation"),
    NavDrawerJC("Nav Drawer JC"),
    NoteScreen("Note Screen"),
    TaskScreen("Task Screen"),
    WelcomeScreen("Welcome Screen"),
    TabRowScreen("Tab Row Screen"),
    MovieScreen("Movie Screen"),
    CrudFireStoreScreen("Crud FireStore Screen"),
    FirebaseStorageScreen("Firebase Storage Screen"),
    MyServiceScreen("My Service Screen"),
    MyPeriodicWorkerUI("My Periodic Worker UI"),
    ImageUploadWorkerUI("Image Upload Worker"),
    OneTimeWorkRequest("One Time Work Request"),
    StylesScreen("Styles Screen"),
    PagingScreen("Paging Screen"),
    LoginJetpackComposeScreen("Login JetpackCompose Screen"),
    SouthAmericanQualifiersScreen("South American Qualifiers")
}